apiVersion: v1
kind: ServiceAccount
metadata:
  name: xcluster-cni
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: xcluster-cni
rules:
  - apiGroups:
    - ""
    resources:
      - nodes
    verbs:
      - list
      - get
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: xcluster-cni
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: xcluster-cni
subjects:
- kind: ServiceAccount
  name: xcluster-cni
  namespace: default                         
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: xcluster-cni
spec:
  selector:
    matchLabels:
      app: xcluster-cni
  template:
    metadata:
      labels:
        app: xcluster-cni
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          operator: Exists
      serviceAccountName: xcluster-cni
      serviceAccount: xcluster-cni
      hostNetwork: true
      containers:
      - name: mconnect
        image: registry.nordix.org/cloud-native/xcluster-cni:master
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
