apiVersion: v1
kind: Pod
metadata:
  namespace: kube-system
  name: xcluster-cni
  labels:
    app: xcluster-cni
spec:
  nodeSelector:
    kubernetes.io/os: linux
  tolerations:
    - effect: NoSchedule
      operator: Exists
    - key: CriticalAddonsOnly
      operator: Exists
    - effect: NoExecute
      operator: Exists
  hostNetwork: true
  priorityClassName: system-node-critical
  initContainers:
    - name: install
      image: registry.nordix.org/cloud-native/xcluster-cni:latest
      imagePullPolicy: IfNotPresent
      command: ["/xcluster-cni.sh", "install"]
      securityContext:
        privileged: true
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBERNETES_SERVICE_HOST
          value: "192.168.1.1"
        - name: KUBERNETES_SERVICE_PORT
          value: "6443"
      volumeMounts:
        - mountPath: /cni/bin
          name: cni-bin-dir
          readOnly: false
        - mountPath: /cni/net.d
          name: cni-net-dir
          readOnly: false
  containers:
    - name: xcluster-cni
      image: registry.nordix.org/cloud-native/xcluster-cni:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: LOG_LEVEL
          value: "debug"
        - name: KUBECONFIG
          value: "/cni/net.d/xcluster-cni.kubeconfig"
      securityContext:
        capabilities:
          add: ["NET_ADMIN"]
      volumeMounts:
        - mountPath: /cni/net.d
          name: cni-net-dir
          readOnly: true
  volumes:
    - name: cni-bin-dir
      hostPath:
        path: /opt/cni/bin
    - name: cni-net-dir
      hostPath:
        path: /etc/cni/net.d

