#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
topd=$(readlink -f $dir/../..)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}
findf() {
	f=$ARCHIVE/$1
	test -r $f || f=$HOME/Downloads/$1
	test -r $f || die "Not found [$f]"
}

test -n "$1" || die "No out-file"

mkdir -p $tmp
cp -R $dir/default/* $tmp
cp $topd/_output/xcluster-cni $tmp/bin

if test "$INSTALL_BINARIES" = "yes"; then
	f=$GOPATH/src/github.com/Nordix/ipam-node-annotation/_output/kube-node
	mkdir -p $tmp/opt/cni/bin
	if test -x $f; then
		cp $f $tmp/opt/cni/bin
	else
		findf kube-node.xz
		xz -dc $f > $tmp/opt/cni/bin/kube-node
		chmod a+x $tmp/opt/cni/bin/kube-node
	fi
	log "kube-node version $($tmp/opt/cni/bin/kube-node -version)"
fi

mkdir -p $tmp/etc/kubernetes
sed -e 's,:latest,:local,' < $topd/xcluster-cni.yaml > $tmp/etc/kubernetes/xcluster-cni.yaml
sed -e 's,:latest,:local,' < $topd/xcluster-cni-secondary-net.yaml > $tmp/etc/kubernetes/xcluster-cni-secondary-net.yaml

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
